Task/service menu
DoocaCommerce/lw-storefront pull request #41
Opened 2022-05-31 12:18 UTC by diovaniBelleboni

Changes:

- Adicionado módulo de menu com busca individual de menu por Id

2022-05-31 13:02 UTC, diovaniBelleboni commented
Deve-se fazer ajuste na interface do atributo "children". Aguardando reftoração da api.

2022-06-03 16:52 UTC, tiagotermedooca requested changes

2022-06-03 16:52 UTC, tiagotermedooca commented on src/core/index.ts
> +import { MenuService } from './modules/menu/MenuService'
organizar imports

2022-06-03 16:52 UTC, tiagotermedooca commented on src/core/modules/menu/MenuRepository.ts
> +    const queryFields: String = (fields ? fields : [ ...MENU_QUERY_DEFAULT_FIELDS, menuValuesField ])
isso está um pouco confuso, podemos ver uma forma melhor

2022-06-03 18:22 UTC, diovaniBelleboni commented on src/core/modules/menu/MenuRepository.ts
> +    const queryFields: String = (fields ? fields : [ ...MENU_QUERY_DEFAULT_FIELDS, menuValuesField ])
@tiagotermedooca esta parte é uma das que dependem da reestruturação da api para prosseguir, mas ajustei o que foi feito para uma estrutura que acredito que tenha ficado melhor em comparação ao que tu apontaste.

2022-06-03 18:22 UTC, diovaniBelleboni commented on src/core/index.ts
> +import { MenuService } from './modules/menu/MenuService'
@tiagotermedooca ajustado.

2022-06-07 12:18 UTC, merged