Feat/implementar-mutations
DoocaCommerce/lw-storefront pull request #42
Opened 2022-06-01 18:09 UTC by diovaniBelleboni

Changes:

- Implementado método de mutations em GraphqlService;

2022-06-03 16:54 UTC, tiagotermedooca requested changes

2022-06-03 16:54 UTC, tiagotermedooca commented on src/core/services/GraphqlService.ts
> +    if (!api_url && !token && !domain) console.error('api_url and token are required')
ajustar mensagem de erro

2022-06-03 16:54 UTC, tiagotermedooca commented on src/env.d.ts
> +  token?: string,
mudar interface já que os campos são obrigatórios

2022-06-03 17:35 UTC, diovaniBelleboni commented on src/core/services/GraphqlService.ts
> +    if (!api_url && !token && !domain) console.error('api_url and token are required')
@tiagotermedooca ajustado

2022-06-03 17:35 UTC, diovaniBelleboni commented on src/env.d.ts
> +  token?: string,
@tiagotermedooca ajustado

2022-06-07 11:31 UTC, tiagotermedooca approved these changes

2022-06-07 12:20 UTC, merged